### ISSUE TITLE
程序的一些建议和问题

### ISSUE THREAD

**Issue by Xing-Fax** [jiesou/MFWL-Minecraft-For-Windows-Unlock-Launcher#1]
程序一些问题和建议如下
1.在控制台窗口下输入并执行“Start Minecraft:”可以打开MinecraftUWP，不理解为什么要使用快捷方式打开？
2.在注册表中含有很多多余的项目，完全可以将其删除并且不影响脚本正常运行(详情参见附件)
3.脚本中采用Taskkill方式结束进程，这样会结束系统中所有RuntimeBroker.exe，这样是否会造成一些问题？
4.脚本“Unlock.bat”在360杀毒引擎中会报毒(virus.bat.unsafe.1),其他脚本正常，是否考虑做免杀处理？
5.根据条目2，只需要修改其中一项的值即可实现导入，所以可以通过命令来导入注册表值实现过程(详情参见附件)

如果你感兴趣的话可以参考 https://github.com/xingchuanzhen/Memory_Modification 此方法无需申请管理员权限，不会修改系统设置，通过修改游戏内存的方式实现绕过验证。

![Snipaste_2022-01-27_18-27-20](https://user-images.githubusercontent.com/78350684/151346190-62f559e6-cfb8-408b-b852-88fefec9552d.png)

![Snipaste_2022-01-27_19-28-13](https://user-images.githubusercontent.com/78350684/151350467-6b351876-e866-45f0-ad10-7d11d7ae5576.png)

**Comment by jiesou** [comment]
感谢大佬的建议
会一点点完善的

**Comment by Xing-Fax** [comment]
补充：
发现脚本是采用备份文件来还原源Dll的方法，备份文件存放在C盘各修改文件目录下，其实可以使用SFC命令来定位与修复文件,这样可以减少不必要的操作(详情见附件)

![Snipaste_2022-01-28_13-24-23](https://user-images.githubusercontent.com/78350684/151492851-d36c97f9-e81f-40b5-896e-e2ef7dfd0c14.png)

**Comment by jiesou** [comment]
备份文件也是为了让程序知道当前处于方案A的已解锁状态。如果不备份文件，脚本判断目前的状态就会很麻烦

**Comment by Xing-Fax** [comment]
或许可以通过计算文件MD5来判断目前状态。
![Snipaste_2022-01-28_14-08-58](https://user-images.githubusercontent.com/78350684/151496584-ea90eb12-17a3-41de-be20-30ce6977f27a.png)

**Comment by jiesou** [comment]
不知道为什么有时候没法修复哎
![image](https://user-images.githubusercontent.com/84175239/151506396-c7e6491f-8540-4dae-a9e3-fc82304536ae.png)

**Comment by Xing-Fax** [comment]
无法修复可能是系统部署映像有损坏，可以通过“DISM.exe /Online /Cleanup-image /Scanhealth”，“DISM.exe /Online /Cleanup-image /Restorehealth”这两条命令来修复，无法输出日志是因为需要脱机来修复而不是在联机状态下

**Comment by jiesou** [comment]
![image](https://user-images.githubusercontent.com/84175239/151512305-97c1bdba-d2f6-423f-a83a-85402d03c4e4.png)
日志

**Comment by jiesou** [comment]
感觉还是直接备份文件方便一点

**Comment by Xing-Fax** [comment]
确实

**Comment by jiesou** [comment]
不考虑添加 修改游戏内存绕过验证的方法
PowerShell 编辑内存相关的资料太少了，https://youtu.be/uybCN2T1dj8 这里的方法似乎也没用
